In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
tf.set_random_seed(777)

C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.

In [2]:
xy=pd.read_csv('winequality-red.csv')
xy.drop(xy.columns[[2,4,5,6,7,8,9]], axis='columns')
xy=xy.values
np.random.shuffle(xy)
test_line=int(len(xy)*0.7)
x_data=xy[:test_line,:-1]
y_data=xy[:test_line,[-1]] 
x_test=xy[test_line:,:-1]
y_test=xy[test_line:,[-1]] 

In [3]:
X = tf.placeholder(tf.float32, shape=[None, x_data.shape[1]])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([x_data.shape[1], 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

Instructions for updating:
Colocations handled automatically by placer.


In [4]:
# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    print('Prediction data : ')
    for step in range(501):
        _, cost_val, hy_val = sess.run([train, cost, hypothesis], feed_dict={X: x_data, Y: y_data})
        print(hy_val)
    print("Cost test : ", cost_val, "\n")

Prediction data : 
[[ 74.5395  ]
 [119.64576 ]
 [ 95.04225 ]
 ...
 [ 20.737299]
 [104.72499 ]
 [ 41.94584 ]]
[[-53692.4  ]
 [-86833.89 ]
 [-48329.168]
 ...
 [-12363.9  ]
 [-82640.555]
 [-23330.826]]
[[40050560.]
 [64827740.]
 [35832550.]
 ...
 [ 9183881.]
 [61749524.]
 [17362252.]]
[[-2.9867520e+10]
 [-4.8345985e+10]
 [-2.6718777e+10]
 ...
 [-6.8476795e+09]
 [-4.6051213e+10]
 [-1.2946499e+10]]
[[2.2273507e+13]
 [3.6053717e+13]
 [1.9925301e+13]
 ...
 [5.1065877e+12]
 [3.4342416e+13]
 [9.6547373e+12]]
[[-1.6610314e+16]
 [-2.6886811e+16]
 [-1.4859154e+16]
 ...
 [-3.8082025e+15]
 [-2.5610619e+16]
 [-7.1999543e+15]]
[[1.2387031e+19]
 [2.0050659e+19]
 [1.1081116e+19]
 ...
 [2.8399412e+18]
 [1.9098950e+19]
 [5.3693171e+18]]
[[-9.2375477e+21]
 [-1.4952649e+22]
 [-8.2636690e+21]
 ...
 [-2.1178677e+21]
 [-1.4242921e+22]
 [-4.0041330e+21]]
[[6.8888403e+24]
 [1.1150840e+25]
 [6.1625764e+24]
 ...
 [1.5793857e+24]
 [1.0621561e+25]
 [2.9860557e+24]]
[[-5.1373067e+27]
 [-8.3156635e+27]
 [-4.5957017e+2

[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
