In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
tf.set_random_seed(777)

In [ ]:
xy=pd.read_csv('winequality-red.csv')
xy=xy.values
np.random.shuffle(xy)
test_line=int(len(xy)*0.7)
x_data=xy[:test_line,:-1]
y_data=xy[:test_line,[-1]] 
x_test=xy[test_line:,:-1]
y_test=xy[test_line:,[-1]] 

In [ ]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, x_data.shape[1]])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([x_data.shape[1], 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [1]:
# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())
    print('Prediction data : ')
    for step in range(501):
        _, cost_val, hy_val = sess.run([train, cost, hypothesis], feed_dict={X: x_data, Y: y_data})
        print(hy_val)
    print("Cost test : ", cost_val, "\n")

C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\USER\Anaconda3\envs\su\lib\site-packages\tensorflow\python\framework\dtypes.

Instructions for updating:
Colocations handled automatically by placer.
Prediction data : 
[[ 77.06461 ]
 [ 78.53445 ]
 [103.96241 ]
 ...
 [ 25.372923]
 [ 24.389702]
 [ 31.88859 ]]
[[-48786.832]
 [-44100.47 ]
 [-77113.96 ]
 ...
 [-18110.344]
 [-13657.566]
 [-22482.21 ]]
[[35038080.]
 [31632098.]
 [55544650.]
 ...
 [13033064.]
 [ 9801005.]
 [16173594.]]
[[-2.5200380e+10]
 [-2.2750075e+10]
 [-3.9951806e+10]
 ...
 [-9.3737411e+09]
 [-7.0484900e+09]
 [-1.1632524e+10]]
[[1.8125372e+13]
 [1.6362988e+13]
 [2.8735380e+13]
 ...
 [6.7420616e+12]
 [5.0696123e+12]
 [8.3666933e+12]]
[[-1.3036685e+16]
 [-1.1769088e+16]
 [-2.0667939e+16]
 ...
 [-4.8492312e+15]
 [-3.6463212e+15]
 [-6.0177479e+15]]
[[9.3766429e+18]
 [8.4649229e+18]
 [1.4865427e+19]
 ...
 [3.4878122e+18]
 [2.6226184e+18]
 [4.3282688e+18]]
[[-6.7441551e+21]
 [-6.0883989e+21]
 [-1.0691964e+22]
 ...
 [-2.5086108e+21]
 [-1.8863195e+21]
 [-3.1131093e+21]]
[[4.8507368e+24]
 [4.3790835e+24]
 [7.6902003e+24]
 ...
 [1.8043193e+24]
 [1.3567363e+2

[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
